### ISSUE TITLE
HypeSquad badge invisible

### ISSUE THREAD

**Issue by sheeepdev** [mr-miner1/Better-Badges#4]
The hypesquad badge is invisible and the gif appears only on hover

Original:
![image](https://user-images.githubusercontent.com/68562536/123512021-4ca7ec80-d685-11eb-98c0-d96b4dd91741.png)

Hover: 
![13-01 | Sat, Jun 26 2021](https://user-images.githubusercontent.com/68562536/123512041-69dcbb00-d685-11eb-849d-ec4ee72ee2ea.png)

I am using betterdiscord

**Comment by mr-miner1** [comment]
ill look into it but it seems to work fine for me

**Comment by mr-miner1** [comment]
fixed.

**Comment by sheeepdev** [comment]
nice thanks
