### ISSUE TITLE
Boost and early supporter badge

### ISSUE THREAD

**Issue by CodaClark** [mr-miner1/Better-Badges#7]
Heya
The early supporter badge has no animation (the little heart is missing)
And the server boosting badge becomes overly big when viewing it
![Capture](https://user-images.githubusercontent.com/88249259/127748753-0ebc0ee1-dbf1-496d-a89d-9dd0d1ce1682.JPG)

**Comment by mr-miner1** [comment]
early supporter badge is only bugged in devilbro's Badges In Chat due to technically limitation i cant really fix that
as for the booster badges, thats also a problem relating to Badges In Chat but i think its one that i can fix, patch soon.

**Comment by mr-miner1** [comment]
fixed
