### ISSUE TITLE
No animations and missing icons

### ISSUE THREAD

**Issue by SuperDasher** [mr-miner1/Better-Badges#8]
I'm not sure if this is a problem caused by the theme itself, and I tried removing and re-adding it multiple times, both from the themes library integrated in discord and from the BetterDiscord website itself, but nothing fixed the problem at hand.
Some badges don't have any animations now and the hypesquad badges don't show anymore, even though I'm still able to hover on them

![demo](https://user-images.githubusercontent.com/72823509/130355669-090dbc4d-44de-4303-a8be-f2c503ad6eb5.gif)

**Comment by IveMalfunctioned** [comment]
Yeah it's weird because I just installed this yesterday and then it started doing this same thing a couple minutes later
