### ISSUE TITLE
Hypesquad badges broken

### ISSUE THREAD

**Issue by Kanta0611** [mr-miner1/Better-Badges#9]
The animation is correctly done, but apparently, the original badge stays in the background while the animation is done.
Doesn't happen with other badges, just these ones.

<img src="'https://i.imgur.com/mEeW9c6.mp4" alt="View">

**Comment by mr-miner1** [comment]
can you resend the attachment?

**Comment by mr-miner1** [comment]
¯\_(ツ)_/¯ works fine for me, you sure u using the latest version (v1.2.9)?
